# Site settings
title: Sinatra Portfolio Project
header-img: img/home-bg.png
email: robindoirin@gmail.com
copyright_name: lasttruth
description: > # this means to ignore newlines until "baseurl:"
  reinforcing the weakspots
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lasttruth
learn_profile: lasttruth
email_username: robindoirin@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
